### ISSUE TITLE
Crash when cancelling out window variation change

### ISSUE THREAD

**Issue by loonaticx** [OpenToontownTools/TTOpenLevelEditor#5]
```
Traceback (most recent call last):
  File "C:\Panda3D-1.11.0-Py37-x64\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Panda3D-1.11.0-Py37-x64\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "G:\Work Folder\Toontown\dev\TTOpenLevelEditor\ttle.py", line 78, in <module>
    ToontownLevelEditor().run()
  File "C:\Panda3D-1.11.0-Py37-x64\direct\showbase\ShowBase.py", line 3173, in run
    self.taskMgr.run()
  File "C:\Panda3D-1.11.0-Py37-x64\direct\task\Task.py", line 535, in run
    self.step()
  File "C:\Panda3D-1.11.0-Py37-x64\direct\task\Task.py", line 489, in step
    self.mgr.poll()
  File "G:\Work Folder\Toontown\dev\TTOpenLevelEditor\toontown\leveleditor\PieMenu.py", line 92, in pieMenuTask
    self.performAction(self.initialState)
  File "G:\Work Folder\Toontown\dev\TTOpenLevelEditor\toontown\leveleditor\PieMenu.py", line 42, in performAction
    self.action(value)
  File "G:\Work Folder\Toontown\dev\TTOpenLevelEditor\toontown\leveleditor\LevelStyleManager.py", line 981, in setCurrent
    messenger.send('select_' + self.name, [self._current])
  File "C:\Panda3D-1.11.0-Py37-x64\direct\showbase\Messenger.py", line 336, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Panda3D-1.11.0-Py37-x64\direct\showbase\Messenger.py", line 421, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "G:\Work Folder\Toontown\dev\TTOpenLevelEditor\toontown\leveleditor\LevelEditor.py", line 2255, in setWindowCount    self.DNATarget = self.createWindows()
  File "G:\Work Folder\Toontown\dev\TTOpenLevelEditor\toontown\leveleditor\LevelEditor.py", line 1819, in createWindows
    newDNAWindows.setCode(self.getCurrent('window_texture'))
TypeError: bad argument type for built-in operation
```

**Steps to reproduce:**
1) Open up any dna that contains windows on a wall.
2) Hold down shift and right click on a window. You'll be given a star-like option to choose between different window layouts.
3) While you're able to alter the layouts of the windows with the numbers, if you were to move your mouse back to the middle to cancel out the operation, the program will immediately crash.

![mspaint_2020-09-28_13-23-24](https://user-images.githubusercontent.com/8785058/94470857-daee5100-018d-11eb-9a04-96d798df6c30.png)

**Comment by drewc5131** [comment]
Fixed in #17
